build:
  - name: Building...
  - os:
    - linux:
      - aarch64
  - compiler:
    - gcc:
      - 8.3.0
  - cmake:
    - 3.12.0
  - boost:
    - 1.7.0
  - step:
    - name: CMake
    - commands:
      - cmake --version
      - cmake %(prop:repodir)s
  - step:
    - name: Build
    - commands:
      - make
  - step:
     - name: Test
     - commands:
       - ctest
