build:
  - name: Building...
  - os:
    - linux:
      - aarch64
  - compiler:
    - gcc:
      - 8.3.0
  - step:
    - name: Build
    - commands:
      - spack list
      - gcc --version
  - step:
     - name: Test
     - commands:
       - find %(prop:repodir)s
