build:
  - name: Building...
  - os:
    - linux:
      - x86_64
  - step:
    - name: Build
    - commands:
      - ls -lah %(prop:repodir)s
      - echo "Hello World"
  - step:
     - name: Test
     - commands:
       - exit 1
       - find %(prop:repodir)s
