build:
  - name: Building...
  - os:
    - linux:
      - aarch64
  - compiler:
    - gcc:
      - 8.3.0
  - boost:
    - 1.70.0
  - step:
    - name: Build
    - commands:
      - spack find
      - $CC --version
      - echo $BOOST_ROOT
      - echo $Boost_ROOT
      - echo $boost_ROOT
  - step:
     - name: Test
     - commands:
       - find %(prop:repodir)s
